apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bs-test4
  description: A sample service demonstrating full Backstage catalog features.
  tags:
    - nodejs
    - demo
  annotations:
    github.com/project-slug: yogi2796-elite/bs-test4
    backstage.io/techdocs-ref: dir:.
    circleci.com/project-slug: github/yogi2796-elite/bs-test4
    backstage.io/kubernetes-id: bs-test4
spec:
  type: service
  lifecycle: production
  owner: team-a
  system: demo-system
  providesApis:
    - demo-api
  consumesApis:
    - calix-api
  dependsOn:
    - resource:default/postgres-db
